opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_none_name
  - empty_collection_literal
  - empty_string
  - first_where
  - last_where
  - modifier_order
  - overridden_super_call
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

disabled_rules:
  - trailing_comma
  - identifier_name

indentation: 2
line_length: 120
